###

GET http://localhost:8080/calendar

###

GET http://localhost:8080/calendar/Calendar1

###

GET http://localhost:8080/appointment

###

POST http://localhost:8080/calendar
Content-Type: application/json

{
  "name": "Calendar1",
  "description": "Test Description",
  "pw": "testpassword"
}

###

POST http://localhost:8080/calendar/asdf/addAppointment
Content-Type: application/json

{
  "title": "Appointment 1",
  "description": "Test Description",
  "date": "2021-01-19T23:00:00",
  "startTime": "01:02",
  "endTime": "03:04"
}

###

DELETE http://localhost:8080/appointment/1
Content-Type: application/json

{
  "calendarName": "Calendar1"
}

###
