###

GET http://localhost:8080/calendar

###

GET http://localhost:8080/calendar/Calendar1

###

GET http://localhost:8080/appointment

###

POST http://localhost:8080/calendar
Content-Type: application/json

{
  "name": "Calendar1",
  "description": "Test Description",
  "pw": "testpassword"
}

###

POST http://localhost:8080/appointment
Content-Type: application/json

{
  "calendarName": "Calendar1",
  "appointment": {
    "title": "Appointment 1",
    "description": "Test Description",
    "date": "2021-01-05",
    "startTime": "01:02:03",
    "endTime": "04:05:06"
  }
}

###

DELETE http://localhost:8080/appointment/1
Content-Type: application/json

{
  "calendarName": "Calendar1"
}

###
